### PR TITLE
Add getSeekableStream method with maxStreamSize parameter

### PR DESCRIPTION
**Pull request by MaximPlusov**

### CODE REVIEW

**Review by bdoubrov — APPROVED** [review]

**Comment by reftel** [comment]
I would have expected this testcase to pass, but it fails in the call to `createConcatenated` due to the copy loop reading `BF_BUFFER_SIZE` bytes, even when that exceeds the `maxSize`. Did I misunderstand the use of `maxSize`?
```
    @Test
    public void shouldThrowExceptionWhenReadingMoreThanMaxSize() throws IOException {
        byte[] alreadyRead = "a".getBytes();
        ByteArrayInputStream stream = new ByteArrayInputStream("bc".getBytes());
        try (InternalInputStream input = InternalInputStream.createConcatenated(alreadyRead, stream, 2)) {
            assertEquals(input.read(), 'a');
            assertEquals(input.read(), 'b');
            assertEquals(input.getCurrentOffset(), 2);
            assertTrue(
                Assertions.assertThrows(VeraPDFParserException.class, () -> input.read())
                    .getMessage()
                    .contains("size exceeded")
            );
        }
    }
    ```

**Comment by MaximPlusov** [comment]
@reftel The VeraPDFParserException should occur when a stream is created (`InternalInputStream.createConcatenated(alreadyRead, stream, 2)`) if it is larger than the specified maximum size

**Comment by reftel** [comment]
Right, so it´s the maximum number of bytes permitted to be written to the temp file, not how many bytes one is allowed to read from the seekable stream. But then, should not this testcase pass?

```
    @Test
    public void shouldThrowExceptionWhenAlreadyReadIsLargerThanMaxSize() {
        byte[] alreadyRead = "abc".getBytes();
        ByteArrayInputStream stream = new ByteArrayInputStream("".getBytes());
        VeraPDFParserException thrown = assertThrows(VeraPDFParserException.class,
            () -> InternalInputStream.createConcatenated(alreadyRead, stream, 2));
        assertTrue(thrown.getMessage().contains("size exceeded"));
    }
```

**Comment by reftel** [comment]
Seems so. Created https://github.com/veraPDF/veraPDF-parser/pull/587 for fixing that.

**Pull request merged**
